spring:
  mustache:
    # 템플릿 파일의 확장자를 .mustache로 지정하여 Mustache
    # 템플릿 파일을 인식하도록 설정
    suffix: .mustache
    # 템플릿 파일이 위치한
    # 기본 경로를 src/main/resources/templates/로 설정
    prefix: classpath:/templates/
    # 개발 중 템플릿 캐시를 비활성화하여 코드
    # 수정 후 바로 반영되도록 함 (프로덕션에서는 true로 설정 권장)
    cache: false
    # 템플릿 파일을 UTF-8 인코딩으로 처리하여 한글 등 다양한 문자 지원
    charset: UTF-8

server:
  # 애플리케이션이 실행될 포트를 8080으로 설정 (기본값은 8080, 필요 시 변경 가능)
  port: 80

logging:
  level:
    # Spring Web 관련 로그를 DEBUG 수준으로
    # 설정하여 요청/응답 세부 사항을 개발 중 확인 가능
    org.springframework.web: DEBUG