server:
  port: 80


spring:
  mustache:
    # ??? ??? ???? .mustache? ???? ??? ??? ????? ??
    suffix: .mustache
    # src/main/resources/templates
    prefix: classpath:/templates/
    # ?? ?? ?? ? ?? ????? ????(?? ?? ??)
    cache: false
    #??? ??? UTF-8 ????? ??
    charset: UTF-8

logging:
  level:
    # Spring Web ?? ??? DEBUG ?? ???? ??
    # ??? ??? ?? ?? ??? ????? ?? ??
    org.spring.framework.web: DEBUG