spring.application.name=class_step_websocket

# UTF-8 ??
server.servlet.encoding.charset=utf-8
server.servlet.encoding.force=true

# 1. DB ??
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa

# 2. ORM -> ??? ??(JPA) -> Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. ??? ?? ????