### 1. 새로운 이슈 생성 (POST)
POST http://localhost:8080/api/issues/save
Content-Type: application/json

{
    "title": "안녕",
    "description": "테스트",
    "reporterId": 1,
    "projectId": 1
}

### 2. 이슈 조회 (GET)
GET http://localhost:8080/api/issues
Content-Type: application/json

### 유저
### 회원가입
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
    "name": "테스트유저",
    "email": "a@b.com",
    "password": "asd1234"
}

### 로그인
POST http://localhost:8080/api/users/login/local
Content-Type: application/json

{
    "email": "a@b.com",
    "password": "asd1234"
}